"""add unique constraint for cart items

Revision ID: 87e4b40169bf
Revises: 1217f4735839
Create Date: 2026-03-12 07:31:08.061080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87e4b40169bf'
down_revision: Union[str, Sequence[str], None] = '1217f4735839'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cart_items_cart_id_movie_id_key'), 'cart_items', type_='unique')
    op.create_unique_constraint('uq_cart_movie', 'cart_items', ['cart_id', 'movie_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_cart_movie', 'cart_items', type_='unique')
    op.create_unique_constraint(op.f('cart_items_cart_id_movie_id_key'), 'cart_items', ['cart_id', 'movie_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
